#!/usr/bin/env bash
# This script reads /etc/passwd and tells a story for each user.

# Redirects the entire /etc/passwd file into the 'while' loop.
# The loop reads the file line by line.
while IFS=':' read -r username password uid gid info home shell
do
  # Inside the loop, we have the 7 variables for each user.
  # Plugs them into the required sentence:
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"

done < /etc/passwd
