#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
i=0 # 1. INITIALIZE the counter

while [ $i -lt 10 ]; do #2. CHECK the counter
	echo "Best School"
	i=$((i+1)) # 3. INCREMENT the counter
done
