#!/usr/bin/env bash
# A script that prints "Best School" 10 times, with "Hi" on the 9th

i=1 #initialize the counter
# Loop as long as $i is less than or equal to 10
while [ "$i" -le 10 ]; do

	# 1. Print "Best School" on every iteration
	echo "Best School"
	
	# 2. Check for the 9th iteration
	if [ "$i" -eq 9 ]; then
	# 3. If it is the 9th print "Hi"
	echo "Hi"
	fi

	# 4. Increment the counter
	((i++))

done
