#!/usr/bin/env bash
# Loops from 1 to 20 and printing bad luck messages for 4,9,17

i=1 # Initialize the counter

# Loop as long as $i is less than or equal to 20
while [ "$i" -le 20 ]; do

	# 1. Print the number on every iteraction
	echo "$i"

	# 2. Use a case statement to check for supersititious numbers
	case "$i" in
		4)
		# if $i is 4, then print this
		echo "bad luck from China"
		;;
		9)
		# if $i is 9, then print this
		echo "bad luck from Japan"
		;;
		17)
		# if $i is 17, then print this
		echo "bad luck from Italy"
		;;
	esac # end of case statement

	# 3. Increment the counter for the next loop
	((i++))

done
