#!/usr/bin/env bash
# This is script that displays the time for 12 hours and 59 minutes, hours from 0 to 12, minutes from 1 to 59

h=0
while [ "$h" -le 12 ]; do

	#  1. print the hour (from the outer loop)
	echo "Hour: $h"

	# 2. start the inner loop for minutes
	# ----
	m=1	# <---- Important: reset the minutes to 1 every time the hour changes.
	while [ "$m" -le 59 ]; do

		# 3. print the minute
		echo "$m"

		((m++))	# 4. increment th minute
	done
	# ----
	# 5. the inner loop (minutes) is finished

	((h++))	# 6. increment the hour and start the outer loop over.
done
