#!/usr/bin/env bash
# This script displays content for the current directory in list format, where only part of the name after first dash is displayed

# loop over every file in the current directory that contains a dash
# 'file' will hold the filename, 1 by 1
for file in *
do
	# check if the filename contains a dash, then use wildcard
	if [[ "$file" == *-* ]]; then
	
		# if yes: the file has a dash. pipe to 'cut'
		echo "$file" | cut -d '-' -f 2-
	else
		# if no: the file does not have a dash, then print whole name.
		echo "$file"
	fi
done
