#!/usr/bin/env bash
#This script for below operations:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/tmp/myscript.pid"

# PID file
echo $$ > "$pid_file"

# Cleanup funtion
cleanup() {
  rm -f "$pid_file"
  exit 0
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT

#loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done
