#!/usr/bin/env bash
# This script finds the PID and name of "bash" processes using pgrep.

# 'pgrep' is a single command that finds processes by name.
# The '-l' flag tells it to list the process name in addition to the PID.
pgrep -l bash
